### ISSUE TITLE
Left panel colour is wrong

### ISSUE THREAD

**Issue by CapitolRadio** [shompoe/sn-tangerine-theme#1]
When selecting a tag/view, the active selection colour is a bright white, not a theme-matching colour.

![image](https://user-images.githubusercontent.com/54081978/197530259-35564d2a-166e-46b6-a71b-70087818e2a2.png)

**Comment by shompoe** [comment]
Hi, and thanks for trying out my theme. I am aware of this issue and so are the Standard Notes dev team. The theme is configured correctly and this issue is a regression caused by recent changes to the app, and it affects all custom themes. Unfortunately the dev team are very busy working on core functionality at the moment and so the priority for this issue is quite low but I am expecting a fix eventually.

**Comment by CapitolRadio** [comment]
> Hi, and thanks for trying out my theme. I am aware of this issue and so are the Standard Notes dev team. The theme is configured correctly and this issue is a regression caused by recent changes to the app, and it affects all custom themes. Unfortunately the dev team are very busy working on core functionality at the moment and so the priority for this issue is quite low but I am expecting a fix eventually.

Thanks for the confirmation :)
